baseURL:  "/"
languageCode: "en-us"
title : "My hugo site"
theme: "hugo-profile"
paginate: 10
# Navigation links
params:
  logo: /img/logo.jpeg


menu:
  main:
    - identifier: home
      name: Home
      url: /home/
      weight: 1
    - identifier: services
      name: Services
      url: /services/
      weight: 2
    - identifier: careers
      name: Careers
      url: /careers/
      weight: 3
    - identifier: portfolio
      name: Portfolio
      url: /portfolio/
      weight: 4
    - identifier: contact
      name: Contact Us
      url: /contact/
      weight: 5
