baseURL:  "/"
languageCode: "en-us"
title : "My hugo site"
theme: "hugo-profile"
paginate: 10
# Navigation links
menu:
  main:
    - name: Home
      url: /home
    - name: Services
      url: /services/
    - name: Careers
      url: /careers/
    - name: Portfolio
      url: /portfolio/
    - name: Contact Us
      url: /contact/
